apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rbitr.fullname" . }}-config
  labels:
    {{- include "rbitr.labels" . | nindent 4 }}
data:
  RBTR_SETUP_TOKEN_REQUIRED: {{ .Values.setup.tokenRequired | quote }}
  {{- if .Values.setup.allowedCIDRs }}
  RBTR_SETUP_ALLOWED_CIDRS: {{ join "," .Values.setup.allowedCIDRs | quote }}
  {{- end }}
  RBTR_LICENSE_KEY_PATH: {{ .Values.license.keyPath | quote }}
  RBTR_LICENSE_PROVIDER: {{ .Values.license.provider | default "self-managed" | quote }}
  {{- if eq .Values.license.provider "aws-marketplace" }}
  RBTR_AWS_PRODUCT_CODE: {{ .Values.aws.productCode | quote }}
  {{- if .Values.aws.region }}
  RBTR_AWS_REGION: {{ .Values.aws.region | quote }}
  {{- end }}
  {{- if .Values.aws.customerID }}
  RBTR_AWS_CUSTOMER_ID: {{ .Values.aws.customerID | quote }}
  {{- end }}
  {{- end }}
  RBTR_FEATURE_RATE_LIMITING: {{ .Values.features.rateLimiting | quote }}
  RBTR_FEATURE_ARG_CONSTRAINTS: {{ .Values.features.argConstraints | quote }}
  RBTR_FEATURE_SHADOW_MODE: {{ .Values.features.shadowMode | quote }}
