{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rbitr.fullname" . }}
  labels:
    {{- include "rbitr.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /setup
            pathType: Prefix
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /api/marketplace
            pathType: Prefix
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /readyz
            pathType: Exact
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-gateway
                port:
                  number: 8080
          {{- if $.Values.ui.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "rbitr.fullname" $ }}-ui
                port:
                  number: 5173
          {{- end }}
    {{- end }}
{{- end }}
