{{- if not .Values.externalDatabase.existingSecret }}
{{- $secretName := include "rbitr.fullname" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "rbitr.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "rbitr.databaseURL" . | quote }}
  {{- if and $existingSecret (not .Values.setup.token) }}
  RBTR_SETUP_TOKEN: {{ index $existingSecret.data "RBTR_SETUP_TOKEN" | b64dec | quote }}
  {{- else }}
  RBTR_SETUP_TOKEN: {{ .Values.setup.token | default (randAlphaNum 32) | quote }}
  {{- end }}
  {{- if and $existingSecret (not .Values.secrets.tenantKeyHmac) }}
  RBTR_TENANT_KEY_HMAC_SECRET: {{ index $existingSecret.data "RBTR_TENANT_KEY_HMAC_SECRET" | b64dec | quote }}
  {{- else }}
  RBTR_TENANT_KEY_HMAC_SECRET: {{ .Values.secrets.tenantKeyHmac | default (randAlphaNum 64) | quote }}
  {{- end }}
  {{- if and $existingSecret (not .Values.secrets.adminKeyHmac) }}
  RBTR_ADMIN_KEY_HMAC_SECRET: {{ index $existingSecret.data "RBTR_ADMIN_KEY_HMAC_SECRET" | b64dec | quote }}
  {{- else }}
  RBTR_ADMIN_KEY_HMAC_SECRET: {{ .Values.secrets.adminKeyHmac | default (randAlphaNum 64) | quote }}
  {{- end }}
{{- end }}
