// Code generated by mockery v2.53.5. DO NOT EDIT.

package policy

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEvaluatorAPI is an autogenerated mock type for the EvaluatorAPI type
type MockEvaluatorAPI struct {
	mock.Mock
}

// Evaluate provides a mock function with given fields: ctx, tenantID, input
func (_m *MockEvaluatorAPI) Evaluate(ctx context.Context, tenantID string, input map[string]any) (Result, error) {
	ret := _m.Called(ctx, tenantID, input)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]any) (Result, error)); ok {
		return rf(ctx, tenantID, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]any) Result); ok {
		r0 = rf(ctx, tenantID, input)
	} else {
		r0 = ret.Get(0).(Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = rf(ctx, tenantID, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockEvaluatorAPI creates a new instance of MockEvaluatorAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluatorAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluatorAPI {
	mock := &MockEvaluatorAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
