// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package policy

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEvaluatorAPI creates a new instance of MockEvaluatorAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluatorAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluatorAPI {
	mock := &MockEvaluatorAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvaluatorAPI is an autogenerated mock type for the EvaluatorAPI type
type MockEvaluatorAPI struct {
	mock.Mock
}

type MockEvaluatorAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluatorAPI) EXPECT() *MockEvaluatorAPI_Expecter {
	return &MockEvaluatorAPI_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockEvaluatorAPI
func (_mock *MockEvaluatorAPI) Evaluate(ctx context.Context, tenantID string, input map[string]any) (Result, error) {
	ret := _mock.Called(ctx, tenantID, input)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (Result, error)); ok {
		return returnFunc(ctx, tenantID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) Result); ok {
		r0 = returnFunc(ctx, tenantID, input)
	} else {
		r0 = ret.Get(0).(Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, tenantID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvaluatorAPI_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockEvaluatorAPI_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - input map[string]any
func (_e *MockEvaluatorAPI_Expecter) Evaluate(ctx interface{}, tenantID interface{}, input interface{}) *MockEvaluatorAPI_Evaluate_Call {
	return &MockEvaluatorAPI_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, tenantID, input)}
}

func (_c *MockEvaluatorAPI_Evaluate_Call) Run(run func(ctx context.Context, tenantID string, input map[string]any)) *MockEvaluatorAPI_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEvaluatorAPI_Evaluate_Call) Return(result Result, err error) *MockEvaluatorAPI_Evaluate_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockEvaluatorAPI_Evaluate_Call) RunAndReturn(run func(ctx context.Context, tenantID string, input map[string]any) (Result, error)) *MockEvaluatorAPI_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}
