FROM golang:1.25.5 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -trimpath -ldflags "-s -w" -o /out/mocktool ./cmd/mocktool

FROM gcr.io/distroless/base-debian12

COPY --from=build /out/mocktool /mocktool

USER nonroot:nonroot

EXPOSE 8090

ENTRYPOINT ["/mocktool"]
