// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package connector

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

type MockConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnector) EXPECT() *MockConnector_Expecter {
	return &MockConnector_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockConnector
func (_mock *MockConnector) Execute(ctx context.Context, req Request) (Response, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Request) (Response, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Request) Response); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(Response)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Request) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnector_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConnector_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req Request
func (_e *MockConnector_Expecter) Execute(ctx interface{}, req interface{}) *MockConnector_Execute_Call {
	return &MockConnector_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *MockConnector_Execute_Call) Run(run func(ctx context.Context, req Request)) *MockConnector_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Request
		if args[1] != nil {
			arg1 = args[1].(Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConnector_Execute_Call) Return(response Response, err error) *MockConnector_Execute_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockConnector_Execute_Call) RunAndReturn(run func(ctx context.Context, req Request) (Response, error)) *MockConnector_Execute_Call {
	_c.Call.Return(run)
	return _c
}
