// Code generated by mockery v2.53.5. DO NOT EDIT.

package connector

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, req
func (_m *MockConnector) Execute(ctx context.Context, req Request) (Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Request) (Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Request) Response); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(Response)
	}

	if rf, ok := ret.Get(1).(func(context.Context, Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockConnector creates a new instance of MockConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnector {
	mock := &MockConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
