// Code generated by mockery v2.53.5. DO NOT EDIT.

package store

import (
	context "context"

	models "github.com/gabrielleeyj/rbitr/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockStoreAPI is an autogenerated mock type for the StoreAPI type
type MockStoreAPI struct {
	mock.Mock
}

// GetAdminKeyByHash provides a mock function with given fields: ctx, keyHash
func (_m *MockStoreAPI) GetAdminKeyByHash(ctx context.Context, keyHash string) (models.AdminKey, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminKeyByHash")
	}

	var r0 models.AdminKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.AdminKey, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.AdminKey); ok {
		r0 = rf(ctx, keyHash)
	} else {
		r0 = ret.Get(0).(models.AdminKey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolicy provides a mock function with given fields: ctx, tenantID
func (_m *MockStoreAPI) GetPolicy(ctx context.Context, tenantID string) (models.Policy, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 models.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Policy, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Policy); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(models.Policy)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTenantByKeyHash provides a mock function with given fields: ctx, keyHash
func (_m *MockStoreAPI) GetTenantByKeyHash(ctx context.Context, keyHash string) (models.Tenant, error) {
	ret := _m.Called(ctx, keyHash)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantByKeyHash")
	}

	var r0 models.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Tenant, error)); ok {
		return rf(ctx, keyHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Tenant); ok {
		r0 = rf(ctx, keyHash)
	} else {
		r0 = ret.Get(0).(models.Tenant)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTool provides a mock function with given fields: ctx, tenantID, toolID
func (_m *MockStoreAPI) GetTool(ctx context.Context, tenantID string, toolID string) (models.Tool, error) {
	ret := _m.Called(ctx, tenantID, toolID)

	if len(ret) == 0 {
		panic("no return value specified for GetTool")
	}

	var r0 models.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (models.Tool, error)); ok {
		return rf(ctx, tenantID, toolID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) models.Tool); ok {
		r0 = rf(ctx, tenantID, toolID)
	} else {
		r0 = ret.Get(0).(models.Tool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tenantID, toolID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertADR provides a mock function with given fields: ctx, record
func (_m *MockStoreAPI) InsertADR(ctx context.Context, record models.ActionDecisionRecord) error {
	ret := _m.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for InsertADR")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ActionDecisionRecord) error); ok {
		r0 = rf(ctx, record)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertApprovalRequest provides a mock function with given fields: ctx, req
func (_m *MockStoreAPI) InsertApprovalRequest(ctx context.Context, req models.ApprovalRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for InsertApprovalRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ApprovalRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListEvidence provides a mock function with given fields: ctx, tenantID, limit
func (_m *MockStoreAPI) ListEvidence(ctx context.Context, tenantID string, limit int) ([]models.ActionDecisionRecord, error) {
	ret := _m.Called(ctx, tenantID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListEvidence")
	}

	var r0 []models.ActionDecisionRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]models.ActionDecisionRecord, error)); ok {
		return rf(ctx, tenantID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []models.ActionDecisionRecord); ok {
		r0 = rf(ctx, tenantID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ActionDecisionRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, tenantID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkBootstrapComplete provides a mock function with given fields: ctx
func (_m *MockStoreAPI) MarkBootstrapComplete(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MarkBootstrapComplete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePolicy provides a mock function with given fields: ctx, tenantID, regoModule, policyVersion
func (_m *MockStoreAPI) UpdatePolicy(ctx context.Context, tenantID string, regoModule string, policyVersion string) error {
	ret := _m.Called(ctx, tenantID, regoModule, policyVersion)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePolicy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, regoModule, policyVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTenantConfig provides a mock function with given fields: ctx, tenantID, name, tenantKey
func (_m *MockStoreAPI) UpdateTenantConfig(ctx context.Context, tenantID string, name string, tenantKey string) error {
	ret := _m.Called(ctx, tenantID, name, tenantKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTenantConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, name, tenantKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateToolConfig provides a mock function with given fields: ctx, tenantID, toolID, baseURL, authType, authValue
func (_m *MockStoreAPI) UpdateToolConfig(ctx context.Context, tenantID string, toolID string, baseURL string, authType string, authValue string) error {
	ret := _m.Called(ctx, tenantID, toolID, baseURL, authType, authValue)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToolConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = rf(ctx, tenantID, toolID, baseURL, authType, authValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStoreAPI creates a new instance of MockStoreAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreAPI {
	mock := &MockStoreAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
